package com.reprezen.rapidml.realization.model;

public enum MethodTypeSelector {

	READ_METHOD, WRITE_METHOD, GET_METHOD, POST_METHOD, PUT_METHOD, PATCH_METHOD, DELETE_METHOD, OPTIONS_METHOD, HEAD_METHOD, TRACE_METHOD, CONNECT_METHOD
}
