/*
 * generated by Xtext
 */
package com.reprezen.rapidml.xtext.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractXtextDslJavaValidator extends com.reprezen.rapidml.xtext.validation.RepreZenTerminalsJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.modelsolv.com/reprezen/rapidml/1.0"));
		return result;
	}

}
