/*******************************************************************************
 * Copyright © 2013, 2016 Modelsolv, Inc.
 * All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property
 * of ModelSolv, Inc. See the file license.html in the root directory of
 * this project for further information.
 *******************************************************************************/
/*
* generated by Xtext
*/
package com.reprezen.rapidml.xtext.validation;

import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.EValidatorRegistrar;

import com.reprezen.rapidml.RapidmlPackage;

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class RepreZenTerminalsJavaValidator
        extends com.reprezen.rapidml.xtext.validation.AbstractRepreZenTerminalsJavaValidator {

    @Override
    public void register(EValidatorRegistrar registrar) {
        super.register(registrar);
    }

    @Override
    protected List<EPackage> getEPackages() {
        List<EPackage> result = super.getEPackages();
        result.add(RapidmlPackage.eINSTANCE);
        return result;
    }

    // @Check
    // public void checkGreetingStartsWithCapital(Greeting greeting) {
    // if (!Character.isUpperCase(greeting.getName().charAt(0))) {
    // warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
    // }
    // }
}
