/*
 * generated by Xtext
 */
package com.reprezen.rapidml.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.reprezen.rapidml.xtext.services.XtextDslGrammarAccess;

public class XtextDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XtextDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_ML_COMMENT_NL", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.reprezen.rapidml.xtext.parser.antlr.internal.InternalXtextDslParser createParser(XtextTokenStream stream) {
		return new com.reprezen.rapidml.xtext.parser.antlr.internal.InternalXtextDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ZenModel";
	}
	
	public XtextDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XtextDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
