/*
 * generated by Xtext 2.9.2
 */
package com.reprezen.rapidml.xtext.tests

import com.google.common.io.Resources
import com.google.inject.Inject
import com.reprezen.rapidml.ZenModel
import java.nio.charset.Charset
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(RapidMLInjectorProvider)
class RapidMLParsingTest{

	@Inject
	ParseHelper<ZenModel> parseHelper;

	@Test 
	def void loadModel() {
		val resource = Resources.toString(Resources.getResource("TaxBlaster.rapid"), Charset.forName("UTF-8"))
		val result = parseHelper.parse(resource)

		Assert.assertNotNull(result)
	}

}
