/*
 * generated by Xtext 2.9.2
 */
package com.reprezen.rapidml.xtext.tests

import com.google.common.io.Resources
import com.google.inject.Inject
import com.reprezen.rapidml.ZenModel
import java.nio.charset.Charset
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.util.CancelIndicator
import org.eclipse.xtext.validation.CheckMode
import org.eclipse.xtext.validation.IResourceValidator
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(RapidMLInjectorProvider)
class RapidMLParsingTest{

	@Inject
	ParseHelper<ZenModel> parseHelper
	
	@Inject
	IResourceValidator validator

	@Test 
	def void loadModel() {
		val resource = Resources.toString(Resources.getResource("TaxBlaster.rapid"), Charset.forName("UTF-8"))
		val result = parseHelper.parse(resource)

		Assert.assertNotNull(result)
		
		val issues = validator.validate(result.eResource, CheckMode.ALL, CancelIndicator.NullImpl)
		
		Assert.assertEquals(0, issues.size)
	}

}
