/*
 * generated by Xtext 2.15.0
 */
package com.modelsolv.reprezen.restapi.xtext.ide


/**
 * Use this class to register ide components.
 */
class RapidMLIdeModule extends AbstractRapidMLIdeModule {
}
