/*******************************************************************************
 * Copyright © 2013, 2016 Modelsolv, Inc.
 * All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property
 * of ModelSolv, Inc. See the file license.html in the root directory of
 * this project for further information.
 *******************************************************************************/
/*
 * generated by Xtext
 */
package com.reprezen.rapidml.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RepreZenTerminalsRuntimeModule extends com.reprezen.rapidml.xtext.AbstractRepreZenTerminalsRuntimeModule {

}
