/*
 * generated by Xtext
 */
package com.reprezen.rapidml.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RepreZenTerminalsRuntimeModule extends com.reprezen.rapidml.xtext.AbstractRepreZenTerminalsRuntimeModule {

}
