/*
 * generated by Xtext 2.15.0
 */
package com.modelsolv.reprezen.restapi.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RapidMLStandaloneSetup extends RapidMLStandaloneSetupGenerated {

	def static doSetup() {
		new RapidMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
