/*
 * generated by Xtext 2.9.2
 */
package com.modelsolv.reprezen.restapi.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRapidMLScopeProvider extends DelegatingScopeProvider {
}
